SELECT DISTINCT Class FROM ANIMAL;

SELECT DISTINCT Nutrition FROM ANIMAL;

SELECT DISTINCT Species FROM ANIMAL;

SELECT DISTINCT Zone FROM EXHIBIT;

SELECT DISTINCT Cage_Name FROM EXHIBIT;

SELECT DISTINCT Category FROM FOOD;

SELECT DISTINCT Reason FROM VET;

SELECT DISTINCT Place_Of_Origin FROM PURCHASE;

