SELECT ANIMAL.Class, ANIMAL.Nutrition, ANIMAL.Species, ANIMAL.Name FROM ANIMAL ORDER BY ANIMAL.Class;

SELECT EMPLOYEE.First_Name, EMPLOYEE.Last_Name, EMPLOYEE.Salary, EMPLOYEE.Date_Of_Birth FROM EMPLOYEE ORDER BY EMPLOYEE.Date_Of_Birth;

SELECT VET.Import_Date, VET.Reason FROM VET ORDER BY VET.Import_Date;

SELECT ANIMAL.Class, ANIMAL.Species, ANIMAL.Name, EXHIBIT.Zone, EXHIBIT.Cage_Name FROM ANIMAL INNER JOIN EXHIBIT ON ANIMAL.Exhibit_ID = EXHIBIT.Exhibit_ID  ORDER BY EXHIBIT.Zone;

SELECT Animal_ID, Time, COUNT(*) OVER (PARTITION BY Animal_ID) AS Feeding_Count FROM FEEDING ORDER BY Animal_ID;

SELECT Animal_ID, DATE(Time) as Date, COUNT(*) AS Feeding_Count FROM FEEDING GROUP BY Animal_ID, DATE(Time) ORDER BY Animal_ID, DATE(Time);

SELECT EMPLOYEE.First_Name, EMPLOYEE.Last_Name, EXHIBIT.Cage_Name, EXHIBIT.Zone FROM EMPLOYEE INNER JOIN EXHIBIT ON EMPLOYEE.Employee_ID = EXHIBIT.Employee_ID ORDER BY EMPLOYEE.Employee_ID;

SELECT ANIMAL.Class, ANIMAL.Species, ANIMAL.Name, PURCHASE.Place_OF_Origin, PURCHASE.Price FROM ANIMAL INNER JOIN PURCHASE ON ANIMAL.Purchase_ID = PURCHASE.Purchase_ID ORDER BY PURCHASE.Purchase_Date DESC;

SELECT ANIMAL.Class, ANIMAL.Species, ANIMAL.Name, VET.Reason, VET.Import_Date, VET.Export_Date FROM ANIMAL INNER JOIN VET ON ANIMAL.Animal_ID = VET.Animal_ID ORDER BY VET.Import_Date, VET.Medical_Case_ID;

SELECT ANIMAL.Species, ANIMAL.Nutrition, FOOD.Name, FOOD.Category, EATING.Amount FROM ANIMAL INNER JOIN EATING ON ANIMAL.Animal_ID = EATING.Animal_ID INNER JOIN FOOD ON EATING.Food_ID = FOOD.Food_ID ORDER BY ANIMAL.Animal_ID;

SELECT EMPLOYEE.First_Name, EMPLOYEE.Last_Name, ANIMAL.Species, ANIMAL.Name, FEEDING.Time FROM EMPLOYEE INNER JOIN FEEDING ON EMPLOYEE.Employee_ID = FEEDING.Employee_ID INNER JOIN ANIMAL ON FEEDING.Animal_ID = ANIMAL.Animal_ID ORDER BY ANIMAL.Animal_ID;

