SELECT COUNT(*) AS Rich_Employees, AVG(Salary) AS Average_Salary FROM EMPLOYEE WHERE Salary > (SELECT AVG(Salary) FROM EMPLOYEE);

SELECT COUNT(*) AS Expensive_Purchases, AVG(Price) AS Average_Price FROM PURCHASE WHERE Price > (SELECT AVG(Price) FROM PURCHASE);

SELECT COUNT(*) AS Old_Animals, AVG(Age) AS Average_Age FROM ANIMAL WHERE Age > (SELECT AVG(Age) FROM ANIMAL);

SELECT COUNT(*) AS Keepers FROM EMPLOYEE INNER JOIN EXHIBIT ON EMPLOYEE.Employee_ID = EXHIBIT.Employee_ID;

SELECT COUNT(*) AS Feeders FROM EMPLOYEE INNER JOIN FEEDING ON EMPLOYEE.Employee_ID = FEEDING.Employee_ID;

