SELECT ANIMAL.Class, COUNT(*) AS Animals_Per_Class FROM ANIMAL GROUP BY ANIMAL.Class;

SELECT ANIMAL.Nutrition, COUNT(*) AS Animals_Per_Nutrition FROM ANIMAL GROUP BY ANIMAL.Nutrition;

SELECT ANIMAL.Species, COUNT(*) AS Animals_Per_Species FROM ANIMAL GROUP BY ANIMAL.Species;

SELECT ANIMAL.Age, COUNT(*) AS Animals_Per_Age FROM ANIMAL GROUP BY ANIMAL.Age;

SELECT ANIMAL.Weight, COUNT(*) AS Animals_Per_Weight FROM ANIMAL GROUP BY ANIMAL.Weight;

SELECT ANIMAL.Import_Date, COUNT(*) AS Animals_Per_Import_Date FROM ANIMAL GROUP BY ANIMAL.Import_Date;

SELECT ANIMAL.Name, ANIMAL.Class, ANIMAL.Species, COUNT(*) AS Lunches_Per_Animal FROM ANIMAL LEFT OUTER JOIN EATING ON ANIMAL.Animal_ID = EATING.Animal_ID GROUP BY EATING.Animal_ID;

SELECT EMPLOYEE.Employee_ID, EMPLOYEE.First_Name, EMPLOYEE.Last_Name, COUNT(*) AS Animals_Fed FROM EMPLOYEE INNER JOIN FEEDING ON EMPLOYEE.Employee_ID = FEEDING.Employee_ID INNER JOIN ANIMAL ON ANIMAL.Animal_ID = FEEDING.Animal_ID GROUP BY FEEDING.Employee_ID;

SELECT EXHIBIT.Zone, COUNT(*) AS Animals_Per_Zone FROM EXHIBIT INNER JOIN ANIMAL ON EXHIBIT.Exhibit_ID = ANIMAL.Exhibit_ID GROUP BY EXHIBIT.Zone;

SELECT FOOD.Category, COUNT(*) as Food_Per_Category FROM FOOD GROUP BY FOOD.Category;

SELECT FOOD.Name, FOOD.Category, COUNT(*) AS Lunches FROM FOOD INNER JOIN EATING ON FOOD.Food_ID = EATING.Food_ID GROUP BY EATING.Food_ID;

SELECT PURCHASE.Place_Of_Origin, COUNT(*) AS Purchases_Per_Country FROM PURCHASE GROUP BY PURCHASE.Place_Of_Origin;

SELECT VET.Reason, COUNT(*) AS Cases_Per_Reason FROM VET GROUP BY VET.Reason;

SELECT VET.Import_Date, COUNT(*) AS Cases_Per_Date FROM VET GROUP BY VET.Import_Date;

SELECT PURCHASE.Place_Of_Origin, COUNT(*) AS Animal_Per_Country FROM ANIMAL INNER JOIN PURCHASE ON ANIMAL.Purchase_ID = PURCHASE.Purchase_ID GROUP BY PURCHASE.Place_Of_Origin;

SELECT VET.Reason, COUNT(*) AS Animal_Per_Reason FROM ANIMAL INNER JOIN VET ON ANIMAL.Animal_ID = VET.Animal_ID GROUP BY VET.Reason;

SELECT ANIMAL.Species, ANIMAL.Name, COUNT(*) AS Cases_Per_Animal FROM ANIMAL INNER JOIN VET ON ANIMAL.Animal_ID = VET.Animal_ID GROUP BY VET.Animal_ID;

SELECT ANIMAL.Species, SUM(PURCHASE.Price) AS Total_Price_Per_Species FROM PURCHASE INNER JOIN ANIMAL ON ANIMAL.Purchase_ID = PURCHASE.Purchase_ID GROUP BY ANIMAL.Species;

